version: "3.9"
name: ska-src-maltopuft

services:
  maltopuftdb:
    image: postgres:16.2-alpine3.19
    restart: always
    container_name: "maltopuftdb"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: asdasd
      POSTGRES_DB: "maltopuftdb"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 3s
      retries: 5